### ISSUE TITLE
Hot reloading not working after modifying html templates

### ISSUE THREAD

**Issue by xiaohk** [fi3ework/vite-plugin-web-components-hmr#2]
Hello, thank you so much for this great tool!

After setting it up with the [Vite starter kit](https://vitejs.dev/guide/#trying-vite-online), HMR is now working for CSS modifications. However, if I change the `html` string template in my TypeScript file, the consoles prints `[vite] hot updated: xxx`, but the elements on the webpage do not change. I have to manually reload the webpage to see the change.

Any suggestions on how to fix this issue? Thanks!

**Comment by fi3ework** [comment]
Could you provide a minimal reproduction on https://stackblitz.com to help address this issue? Thanks!

**Comment by xiaohk** [comment]
Thank you so much for your quick response!

Here is a minimal reproduction: https://stackblitz.com/edit/vitejs-vite-c8ekz3?file=src%2Fcomponents%2Fdemo-page%2Fdemo-page.ts

1. Modifying HTML in `src/components/demo-page/demo-page.ts` doesn't change the output
2. Modifying styles in `src/components/demo-page/demo-page.scss` does change the output

**Comment by fi3ework** [comment]
`render` function should not use arrow function method https://stackblitz.com/edit/vitejs-vite-kzzqfq?file=src%2Fcomponents%2Fdemo-page%2Fdemo-page.ts. I'm not quite sure about the underlying cause. But could be related to the prototype.

**Comment by xiaohk** [comment]
Very interesting! Thank you so much! 🙏 Hot reloading is working now after I changed the arrow function for `render()`.
